extend type Mutation {
  addRoleToUser(userId: String!, roleId: String!): Boolean!
  createUser(email: String!, username: String, password: String): User!
  setUserPassword(userId: String!, password: String!): Boolean!
}
