extend type Mutation {
  createAuthTokenGoogle(
    googleIdToken: String!,
    clientType: AuthClientType!
  ): AuthToken!
  # username can also be email
  createAuthTokenLocal(username: String!, password: String!): AuthToken!
  # requires auth
  createAuthToken(userId: String!): AuthToken!
}
