extend type Mutation {
  createContainer(container: CreateContainerInput!): Container!
  deleteContainers(ids: [String!]!): Boolean!

  updateContainerPorts(containerId: String!, ports: [ContainerPortInput!]!): Boolean!
  updateContainerVariables(containerId: String!, variables: [ContainerVariableInput!]!): Boolean!
  updateContainerVolumes(containerId: String!, volumes: [ContainerVolumeInput!]!): Boolean!

  startContainer(containerId: String!): Boolean!
  stopContainer(containerId: String!): Boolean!
  redeployContainer(containerId: String!): Boolean!
}

input CreateContainerInput {
  name: String!
  image: String!
  tag: String!
  hostId: String!
  networkName: String!
}

input ContainerPortInput {
  containerPort: Int!
  hostPort: Int
  hostBindIp: String
}

input ContainerVariableInput {
  name: String!
  value: String!
}

input ContainerVolumeInput {
  hostPath: String!
  containerPath: String!
}
