type Container {
  _id: String!
  name: String!
  image: String!
  tag: String!
  status: ContainerStatus!
  host: Host!
  networkName: String!

  ports: [ContainerPort!]!
  variables: [ContainerVariable!]!
  volumes: [ContainerVolume!]!
}
