version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - publish:
          context: ah-global
          requires:
            - build
            - lint
          filters:
            branches:
              only: main

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
          - v2-dependencies-
      - run:
          name: Install NPM modules
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  lint:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint
  build:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Authenticate Docker
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"
      - run:
          name: Build Docker image
          command: |
            docker build -t "$DOCKER_REPO:latest" -f docker/dist.Dockerfile .
      - run:
          name: Push Docker image
          command: |
            docker push "$DOCKER_REPO:latest"
