version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - build
            - lint
          filters:
            branches:
              only: master

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Install NPM modules
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
  lint:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Lint
          command: npm run lint
  build:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: npm run build
      - save_cache:
          paths:
            - dist
          key: v1-dist-{{ .Revision }}
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dist-{{ .Revision }}
          - v1-dist-
      - run:
          name: Build and deploy Docker
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin https://registry.alexhicks.net
            docker build -t "$DOCKER_REPO:latest" -f docker/dist.Dockerfile .
            docker push "$DOCKER_REPO:latest"
