extend type Mutation {
  addPermissionsToRole(roleId: String!, permissions: [RolePermissionInput!]!): Boolean!
  createRole(name: String!): Role!
}

input RolePermissionInput {
  action: String!
  resource: String!
}
